title: damianfedeczko.github.io
author: Damian Fedeczko
email: damianfedeczko1+blog@gmail.com
# social links
github_username: damianfedeczko # DO NOT include the @ character, or else the build will fail!
linkedin: https://www.linkedin.com/in/damian-fedeczko-060765123/
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
show_excerpts: true # set to false to remove excerpts on the homepage
plugins: [jekyll-youtube, jekyll-include-cache]
